### ISSUE TITLE
Nexus v2 Ideas / Checklist

### ISSUE THREAD

**Issue by tgriesser** [graphql-nexus/nexus#984]
Adding this as a running list of plans/ideas, will continue to add to it:

- [ ] Drop official support for GraphQL 14
- [ ] Continue to refine [nexus-decorators](https://github.com/graphql-nexus/nexus-decorators) APIs & add into core: `import { nxs } from 'nexus/decorators'`
- [ ] Add additional builder api for constructing field `args`:

```ts
t.field('users', {
  args(a) {
    a.field('status', { type: 'Status' })
    a.list.id('ids')
  }
})
```
- [ ] Docs for schema stitching & [`mergeSchema`](https://github.com/graphql-nexus/nexus/pull/983)
- [ ] Deprecate `nullabilityGuardPlugin` / remove from core
- [ ] More configuration for type generation, along the lines of #967
- [ ] Add `extendType({ name })` syntax, for consistency with other definition blocks
- [ ] Remove `export *` from plugins, only export the top level API, not all of the types

**Comment by jcpage** [comment]
Since it seems more and more people are using subscriptions these days, enhancing the SubscriptionBuilder support (or refactoring somehow so it works the same as ObjectDefinitionBlock, etc) would be great!

I was recently trying to write a plugin to support automatically generating "graphql relay modern" style Input/Payload types for subscriptions (similar to an existing one, "nexus-plugin-relay-mutation" for mutations) and eventually realized subscriptions use a completely different builder that is not extensible with plugins.  Was confused why my added dynamicOutputMethod wasn't showing up in the typeBuilder...
